#!/usr/bin/env python3
"""Check that every internal link on the SPARTA web site resolves.

Both halves of a link matter.  The file has to be there, and so does the
anchor: an anchor name is part of a URL, so a link to "#machine" where the
page defines "#machines" is as dead as a link to a page that was renamed.

Run it against the repository root, which is what GitHub Pages serves:

    python3 utils/link-check.py .

The manual under doc/ is checked as a link target -- the site links into
it constantly -- but not walked as a source, because it is a separate
project with its own sources in the SPARTA repository.  When doc/ is
absent the links into it are counted and skipped rather than reported.

Exits non-zero if anything outside KNOWN_BROKEN does not resolve.
"""
import argparse
import html
import pathlib
import re
import sys

# <a name="..."> is what txt2html emits for ":link(name)"; id="..." covers
# anything hand-written or generated by another tool.  Both are scoped to
# inside a tag, because the manual's prose contains things like
# 'the default mixture has an ID = "all"', which is text, not an anchor.
NAME = re.compile(r'<a\b[^>]*?\bname\s*=\s*"([^"]+)"', re.I)
TAG = re.compile(r'<[a-zA-Z][^>]*>')
ID = re.compile(r'\bid\s*=\s*"([^"]+)"', re.I)
HREF = re.compile(r'<a\b[^>]*?href\s*=\s*"([^"]*)"', re.I)

# The manual lives in the SPARTA repository; its pages are copied in under
# doc/ when a release is made.  If doc/ is absent -- a checkout taken
# between releases -- links into it are counted and skipped rather than
# reported.  Once it is there they are checked like any other link.
MANUAL = 'doc'

# Links that do not resolve and that no edit here can fix.
#
# These are missing files rather than bad links: three patch
# listings this repository has never carried (the patches on either side
# of those dates are present) and a 165 MB QuickTime movie, which is
# presumably why it was never committed.  Adding the file or dropping the
# reference is an editorial call.
KNOWN_BROKEN = {
    'bug.html': {'patches/files.11Jun16', 'patches/files.24May16',
                 'patches/files.4Apr17'},
    'pictures.html': {'movies/rti_longtime.mov'},
}


def anchors(text):
    found = set(NAME.findall(text))
    for tag in TAG.finditer(text):
        found |= set(ID.findall(tag.group(0)))
    return found


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('html_dir')
    args = ap.parse_args()
    root = pathlib.Path(args.html_dir)
    if not root.is_dir():
        print(f'no such directory: {root}', file=sys.stderr)
        return 2

    # Every page in the tree, keyed by its path below the root, so that a
    # link from bench/plot_free.html into ../index.html is resolved against
    # the directory it was written in.  The manual under doc/ is indexed as
    # a link target -- the site links into it constantly -- but not walked
    # as a source: it is a separate project and checks its own links.
    pages = sorted(p for p in root.rglob('*.html')
                   if p.relative_to(root).parts[0] != MANUAL)
    have = {p.relative_to(root).as_posix(): anchors(p.read_text(errors='replace'))
            for p in root.rglob('*.html')}

    bad = []
    known = 0
    unbuilt = set()
    for page in pages:
        name = page.relative_to(root).as_posix()
        text = page.read_text(errors='replace')
        for m in HREF.finditer(text):
            href = html.unescape(m.group(1))
            if href.startswith(('http', 'mailto', 'ftp', 'javascript:')):
                continue
            target, _, frag = href.partition('#')
            allowed = KNOWN_BROKEN.get(name, ())
            if href in allowed or (target and target in allowed):
                known += 1
                continue
            if target and not (page.parent / target).exists():
                # The manual is a separate project, copied in under doc/ at
                # release time, so it is legitimately absent from a build of
                # the site alone.  Only doc/, and only when it is not there.
                if target.split('/')[0] == MANUAL and not (root / MANUAL).is_dir():
                    unbuilt.add(target)
                    continue
                bad.append(f'{name} -> {target} (no such file)')
                continue
            # the anchor is looked for in the file the link actually reaches
            dest = name
            if target:
                resolved = (page.parent / target).resolve()
                try:
                    dest = resolved.relative_to(root.resolve()).as_posix()
                except ValueError:      # a link that climbs out of the tree
                    continue
            if frag and dest in have and frag not in have[dest]:
                if '#' + frag in allowed:
                    known += 1
                    continue
                bad.append(f'{name} -> {href} (no such anchor)')

    for b in sorted(set(bad)):
        print(f'  {b}')
    if known:
        print(f'  note: {known} link(s) that no edit here can fix, listed '
              f'in KNOWN_BROKEN')
    if unbuilt:
        print(f'  note: {len(unbuilt)} link(s) into doc/ not checked; the '
              f'manual is copied in from the SPARTA repository at release')
    n = len(set(bad))
    print(f'  {n} dead internal link(s) or anchor(s) in {len(pages)} pages')
    return 1 if n else 0


if __name__ == '__main__':
    sys.exit(main())
